import react from '@vitejs/plugin-react'
import basicSsl from '@vitejs/plugin-basic-ssl'
import { defineConfig } from 'vite'

// A phone only offers "Install app" / lets a service worker run on a "secure context" —
// https, or exactly http://localhost. A LAN address like http://192.168.x.x never
// qualifies, no matter what the manifest/service worker say, so testing the real
// install prompt from a phone needs this dev server to speak https. Desktop is
// unaffected: `npm run dev` (this file's default) still serves plain http on 5173
// exactly as before; only the separate `npm run dev:lan` script (below) turns this on,
// for LAN/phone testing. The certificate is self-signed and auto-generated by the
// plugin, so the phone's browser will show a one-time "connection isn't private"
// warning — tap Advanced → Proceed. That warning is only about certificate identity;
// the connection itself is still real TLS, which is all a secure context requires.
const wantsHttps = process.env.LAN_HTTPS === 'true'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), ...(wantsHttps ? [basicSsl()] : [])],
  build: {
    cssMinify: false
  },
  server: {
    https: wantsHttps,
    // Listen on every network interface (0.0.0.0), not just localhost, so the dev
    // server is reachable from a phone on the same Wi-Fi at http://<your-PC-LAN-IP>:5173
    // (Vite prints that exact URL as "Network:" when it starts). Without this, the
    // page never even loads on a phone — "localhost" refused/unreachable.
    host: true,
    port: 5173,
    // Proxy /api/* to the Spring Boot backend. The browser only ever calls the
    // relative path "/api/...", which Vite forwards server-side to the backend on
    // this same machine — so it works identically whether the page was opened as
    // http://localhost:5173 (desktop) or http://<LAN-IP>:5173 (phone). This also
    // sidesteps CORS entirely for dev, since the browser sees it as same-origin.
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
  preview: {
    host: true,
    port: 4173,
  },
})
